### ISSUE TITLE
How to query out of bounds checks etc in tests?

### ISSUE THREAD

**Issue by staffantj** [bloomberg/p1160#14]
I have probably missed something, but there seems to be a logical inconsistency in the test_resource. I want to query eg the bounds_errors() function in a gtest showing case2. But whilst the test_resource is valid those counters show zero, they're seemingly only set in the destructor, after which they are not reachable.

I guess what I'm asking is if it makes sense to expose a perform_checks() member function to trigger things?

**Comment by cppguru** [comment]
There is no inconsistency, and there is.  As P1160 says: we have made minimal changes to our design so that we can present for standardization the deliberately *very* simple design we have and what worked for us for 20+ years.  Any changes to that design could then come from standardization for Library Fundmentals TS 3, then hopefully people using it in real life in the TS, with all sorts of testing frameworks and seeing what could work better, so if it ever gets into the standard, we would have a more "usual", modern design.

As for "exposing a checking function".  First of all, as far as I recall, bounds errors are set in `do_deallocate`, not the destructor.  In the current implementation the destructor is not able to do those checks, because it only knows there are allocations, not *where* they are.  Adding that ability is probably a good trade-off, but it is a trade-off, as it will raise memory use, or put the linked list of allocations into the head of the allocation, which then puts it in "harms way" (because that is the area written by the tested code, which may be bad).

So to enable such a checking function to exists, we need to change the design and decide if that change is worth the consequences.  Because for that we do not have even a day of field experience, we did not propose it.

**Comment by cppguru** [comment]
As for "how to query the counters", the current pattern of use, in our test methodology, is that the `test_resource` aborts tests when it finds an error.  That may or may not result in a core dump that is useful, however an error requires human interaction.  Our unit tests (what we call "test drivers") can be executed in so-called very-very-very-verbose mode (I am not kidding).  In which case all test resources are set into verbose mode, and report all allocations and the counters on destruction.  So the process is different (and IMO much simpler) than the one you are trying to achieve.

Of course we aren't going to standardize the "Bloomberg way of working", so we should make this work for everyone.  Have you been to my C++ Now 2019 talk?  In a lonely slide of "possible future enhancements" I listed "nicer integration with other test frameworks", as well as "destructor should probably report bounds errors".  Those two more or less covers your issue I think.  However the best way to do it is something that I think more people would need to think about than just I.  Like I have never used gtest, I used Boost.Test and Bloomberg's "test drivers" and some other stuff that faded into obscurity.

**Comment by staffantj** [comment]
Experimenting further I found that if I simply enclosed the astring in an inner scope I did get the counters - I had indeed confused myself over which part did what. I had the good fortune to be in your talk, and am looking forward to the possible goodies to come.

**Comment by cppguru** [comment]
Great!  I count on you to "teach me" what possible modifications would make `test_resource` play nice with gtest. ;)
